zap:
  level: info
  format: console
  prefix: "[api_server]"
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true

# system configuration
system:
  env: local # 本地设置为local 生产设置为public
  addr: 8082
  db-type: 'mysql'
  oss-type: local # 控制oss选择走本地还是 其他云服务商 
  use-multipoint: false
  # IP限制次数 一个小时15000次
  iplimit-count: 15000
  #  IP限制一个小时
  iplimit-time: 3600
  #  路由全局前缀
  router-prefix: "api"
  is-auth-check: true # 是否开启权限校验

# mysql connect configuration
mysql:
  host: '127.0.0.1'
  port:  3306
  config: 'parseTime=true&loc=Local'
  db-name: 'api_test'
  username: '****'
  password: '*****'
  max-idle-conns: 50
  max-open-conns: 100
  gorm-log: 2 # 2 Error 3 Warn 4 Info
# 跨域配置
cors:
  mode: allow-all # 放行模式: allow-all, 放行全部; whitelist, 白名单模式, 来自白名单内域名的请求添加 cors 头; strict-whitelist 严格白名单模式, 白名单外的请求一律拒绝
  whitelist:
    - allow-origin: example1.com
      allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id
      allow-methods: POST, GET
      expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type

      allow-credentials: true # 布尔值
    - allow-origin: example2.com
      allow-headers: content-type
      allow-methods: GET, POST
      expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
      allow-credentials: true # 布尔值
